name: CI

on:
  push:
  pull_request:

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node --version
      - run: npm --version
      - run: npm -s run lint || true
      - run: npm -s run test || true
